# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#pyuic5 -x example.ui -o example.py

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(290, 170)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font: 25 8pt \"Calibri Light\";\n"
"background-color: rgb(14, 24, 33);\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.singin_button = QtWidgets.QPushButton(self.centralwidget)
        self.singin_button.setGeometry(QtCore.QRect(20, 120, 120, 25))
        self.singin_button.setStyleSheet("border-color: rgb(121, 143, 140);\n"
"font: 25 8pt \"Calibri Light\";\n"
"background-color: rgb(27, 47, 65);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(121, 143, 140);")
        self.singin_button.setObjectName("singin_button")
        self.singup_button = QtWidgets.QPushButton(self.centralwidget)
        self.singup_button.setGeometry(QtCore.QRect(150, 120, 120, 25))
        self.singup_button.setStyleSheet("border-color: rgb(121, 143, 140);\n"
"font: 25 8pt \"Calibri Light\";\n"
"background-color: rgb(27, 47, 65);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(121, 143, 140);")
        self.singup_button.setObjectName("singup_button")
        self.login_line = QtWidgets.QLineEdit(self.centralwidget)
        self.login_line.setGeometry(QtCore.QRect(20, 30, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.login_line.setFont(font)
        self.login_line.setStyleSheet("border-color: rgb(121, 143, 140);\n"
"color: rgb(255, 255, 255);\n"
"font: 25 8pt \"Calibri Light\";\n"
"background-color: rgb(27, 47, 65);")
        self.login_line.setFrame(False)
        self.login_line.setObjectName("login_line")
        self.pw_line = QtWidgets.QLineEdit(self.centralwidget)
        self.pw_line.setGeometry(QtCore.QRect(20, 70, 250, 30))
        self.pw_line.setStyleSheet("border-color: rgb(121, 143, 140);\n"
"color: rgb(255, 255, 255);\n"
"font: 25 8pt \"Calibri Light\";\n"
"background-color: rgb(27, 47, 65);")
        self.pw_line.setFrame(False)
        self.pw_line.setDragEnabled(False)
        self.pw_line.setObjectName("pw_line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login Window"))
        self.singin_button.setText(_translate("MainWindow", "Sing in"))
        self.singup_button.setText(_translate("MainWindow", "Sing up"))
        self.login_line.setText(_translate("MainWindow", "Login"))
        self.pw_line.setText(_translate("MainWindow", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
